### ISSUE TITLE
LaneSimulator: RuntimeException: Cut Vehicle

### ISSUE THREAD

**Issue by Peter-Knoppers** [Peter-Knoppers/OTSim#8]
When running the testData/junction4arm_dumb_traffic_lights.otsm model an error occurs at time 12:15.400:

java.lang.RuntimeException: Cut vehicle: 259.1505637076564@25, still connected: 177.85015638842904@24
    at nl.tudelft.otsim.Simulators.LaneSimulator.Model.checkForRemainingPointers(Model.java:305)
    at nl.tudelft.otsim.Simulators.LaneSimulator.Movable.cut(Movable.java:546)
    at nl.tudelft.otsim.Simulators.LaneSimulator.Movable.delete(Movable.java:354)
    at nl.tudelft.otsim.Simulators.LaneSimulator.Vehicle.translate(Vehicle.java:192)
    at nl.tudelft.otsim.Simulators.LaneSimulator.Vehicle.move(Vehicle.java:104)
    at nl.tudelft.otsim.Simulators.LaneSimulator.Vehicle.move(Vehicle.java:88)
    at nl.tudelft.otsim.Simulators.LaneSimulator.Model.run(Model.java:166)
    at nl.tudelft.otsim.Simulators.LaneSimulator.Stepper.step(LaneSimulator.java:1135)
    at nl.tudelft.otsim.Events.Scheduler.stepSimulator(Scheduler.java:312)
    at nl.tudelft.otsim.Events.Scheduler.access$2(Scheduler.java:308)
    at nl.tudelft.otsim.Events.Scheduler$FastRun.run(Scheduler.java:416)

Simulation then stops. This error should never happen.

**Comment by Peter-Knoppers** [comment]
Wouter Schakel believes that issue #6 should be fixed first; he believes that disappearing vehicles may subsequently result in Cut vehicles.

**Comment by Peter-Knoppers** [comment]
Problem must be re-written. Recent changes cause the problem to occur much later.
